# Generated by Django 6.0.4 on 2026-04-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_deal_contact_alter_deal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='sales.contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20),
        ),
    ]
